name: Cypress Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Use the Node.js version required for your project

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Cucumber Tests
        run: npx cypress run

      - name: Cypress Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: cypress/reports/mocha
